[project]
name = "trakt-backend"
version = "0.1.0"
description = ""
authors = [
    {name = "Nicolai Frigaard",email = "46283121+jovialen@users.noreply.github.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard] (>=0.141.1,<0.142.0)",
    "sqlmodel (>=0.0.39,<0.0.40)",
    "feedparser (>=6.0.14,<7.0.0)",
    "pydantic-settings (>=2.14.2,<3.0.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
ruff = "^0.16.1"
pre-commit = "^4.6.1"
mypy = "^2.3.0"

[tool.ruff]
line-length = 100
target-version = "py312"

[tool.ruff.lint]
select = [
    "E",
    "F",
    "I",   # import sorting
    "UP",  # pyupgrade
    "B",   # bugbear
]

[tool.ruff.lint.per-file-ignores]
"**/__init__.py" = ["F401"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
