name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"
          cache: "poetry"

      - name: Install dependencies
        run: |
          poetry install

      - name: Run tests with coverage
        run: |
          poetry run pytest --cov
